// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0cnCVzLlncBHMUNaC-Hhs65WSydPidso',
    appId: '1:617880072628:web:15f543b4c16ad04ed982e1',
    messagingSenderId: '617880072628',
    projectId: 'todoapp-project-13sp',
    authDomain: 'todoapp-project-13sp.firebaseapp.com',
    storageBucket: 'todoapp-project-13sp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhht-ANrvo6qpQgtfQc3HWpVemMUooPPg',
    appId: '1:617880072628:android:7ebcfe9bd9c75965d982e1',
    messagingSenderId: '617880072628',
    projectId: 'todoapp-project-13sp',
    storageBucket: 'todoapp-project-13sp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmMd8wA28x8Ov3jJM4KPPNUbgcbu84itg',
    appId: '1:617880072628:ios:f99630d18074fa0ed982e1',
    messagingSenderId: '617880072628',
    projectId: 'todoapp-project-13sp',
    storageBucket: 'todoapp-project-13sp.appspot.com',
    iosBundleId: 'com.spflutter.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmMd8wA28x8Ov3jJM4KPPNUbgcbu84itg',
    appId: '1:617880072628:ios:f99630d18074fa0ed982e1',
    messagingSenderId: '617880072628',
    projectId: 'todoapp-project-13sp',
    storageBucket: 'todoapp-project-13sp.appspot.com',
    iosBundleId: 'com.spflutter.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0cnCVzLlncBHMUNaC-Hhs65WSydPidso',
    appId: '1:617880072628:web:77be23aaf3eac5add982e1',
    messagingSenderId: '617880072628',
    projectId: 'todoapp-project-13sp',
    authDomain: 'todoapp-project-13sp.firebaseapp.com',
    storageBucket: 'todoapp-project-13sp.appspot.com',
  );
}
